global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'spring-tours'
    static_configs:
      - targets: ['spring-tours:8080']
    metrics_path: /actuator/prometheus
    scheme: http
    scrape_interval: 5s
  
