services:
  # Will leverage other database
  spring-tours:
    image: ankeyang/spring-tours:v0.1
    container_name: spring-tours
    ports:
      - "8080:8080"
      - "9092:9092"  # H2 Console port if enabled
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
#      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,prometheus
#      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - MANAGEMENT_SERVER_PORT=8080
#      - MANAGEMENT_ENDPOINTS_WEB_BASE-PATH=/actuator
    networks:
      - spring-tours-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'  # Keep data for 30 days
    depends_on:
      - spring-tours
    networks:
      - spring-tours-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - spring-tours-network

networks:
  spring-tours-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: